version: '3.8'
services:
  app:
    build: .
    ports:
      - "5173:5173"
    environment:
      - API_BASE_URL=http://host.docker.internal:3000
    volumes:
      - .:/app
      - /app/node_modules
